basePath: /
definitions:
  main.Cart:
    description: Cart represents a single item in the cart
    properties:
      amount:
        example: 1
        type: integer
      name:
        example: test product
        type: string
      price:
        example: 1000
        type: integer
    type: object
  main.HttpError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: bad request
        type: string
    type: object
  main.Request:
    description: Request represents the request payload containing multiple cart items
    properties:
      data:
        items:
          $ref: '#/definitions/main.Cart'
        type: array
    type: object
host: http://localhost:6969
info:
  contact: {}
  description: Cart represents a single item in the cart
  title: API Docs
  version: "0.1"
paths:
  /payment:
    post:
      consumes:
      - application/json
      description: Request payment to get iframe token
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.Request'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpError'
      summary: Payment request process
      tags:
      - Payment
  /paymentCallback:
    post:
      description: Paytr Callback API (No request and response needed)
      responses: {}
      tags:
      - Paytr Callback
swagger: "2.0"
