basePath: /
definitions:
  main.Cart:
    description: Cart represents a single item in the cart
    properties:
      amount:
        example: 1
        type: integer
      name:
        example: test product
        type: string
      price:
        example: 1000
        type: integer
    type: object
  main.HttpError:
    description: Error response
    properties:
      code:
        example: 400
        type: integer
      message:
        example: bad request
        type: string
    type: object
  main.HttpSuccess:
    description: Success Response
    properties:
      code:
        example: 200
        type: integer
      iframe:
        type: string
      message:
        example: Success
        type: string
    type: object
  main.Request:
    description: Request represents the request payload containing multiple cart items,
      user name, user email, user address, user phone and total payment
    properties:
      basket:
        items:
          $ref: '#/definitions/main.Cart'
        type: array
      email:
        example: test@test.com
        type: string
      totalPayment:
        example: 1000
        type: integer
      user_address:
        example: Victor Plains Suite 7389
        type: string
      username:
        example: john
        type: string
      userphone:
        example: 1-770-736-8031 x56442
        type: string
    type: object
host: localhost:6969
info:
  contact: {}
  description: Cart represents a single item in the cart
  title: API Docs
  version: "0.1"
paths:
  /payment:
    post:
      consumes:
      - application/json
      description: Request payment to get iframe token
      parameters:
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.HttpSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpError'
      summary: Payment request process
      tags:
      - Payment
  /paymentCallback:
    post:
      description: Paytr Callback API (No request and response needed)
      responses: {}
      tags:
      - Paytr Callback
swagger: "2.0"
